# Generated by Django 5.2 on 2025-04-28 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('calendar_type', models.CharField(choices=[('regular', 'Regular'), ('ritual', 'Ritual'), ('administrative', 'Administrativo'), ('special', 'Especial')], default='regular', max_length=20, verbose_name='tipo de calendario')),
                ('year', models.PositiveIntegerField(verbose_name='año')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(verbose_name='fecha de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendars', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'calendario',
                'verbose_name_plural': 'calendarios',
                'ordering': ['-year', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('date', models.DateField(verbose_name='fecha')),
                ('start_time', models.TimeField(verbose_name='hora de inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='hora de finalización')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='ubicación')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='es virtual')),
                ('virtual_link', models.URLField(blank=True, verbose_name='enlace virtual')),
                ('event_type', models.CharField(choices=[('tenida', 'Tenida Regular'), ('instruction', 'Instrucción'), ('ceremony', 'Ceremonia'), ('social', 'Evento Social'), ('administrative', 'Reunión Administrativa'), ('other', 'Otro')], default='tenida', max_length=20, verbose_name='tipo de evento')),
                ('required_degree', models.PositiveSmallIntegerField(choices=[(1, 'Aprendiz'), (2, 'Compañero'), (3, 'Maestro')], default=1, verbose_name='grado requerido')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('cancelled', 'Cancelado'), ('completed', 'Completado')], default='scheduled', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='asunto')),
                ('content', models.TextField(verbose_name='contenido')),
                ('send_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
                ('is_draft', models.BooleanField(default=False, verbose_name='es borrador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='remitente')),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'ordering': ['-send_date'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='leído')),
                ('read_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de lectura')),
                ('archived', models.BooleanField(default=False, verbose_name='archivado')),
                ('starred', models.BooleanField(default=False, verbose_name='destacado')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_statuses', to='communications.message', verbose_name='mensaje')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_statuses', to=settings.AUTH_USER_MODEL, verbose_name='destinatario')),
            ],
            options={
                'verbose_name': 'destinatario de mensaje',
                'verbose_name_plural': 'destinatarios de mensaje',
                'unique_together': {('message', 'recipient')},
            },
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', through='communications.MessageRecipient', to=settings.AUTH_USER_MODEL, verbose_name='destinatarios'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('content', models.TextField(verbose_name='contenido')),
                ('notification_type', models.CharField(choices=[('general', 'General'), ('important', 'Importante'), ('event', 'Evento'), ('payment', 'Pago'), ('ritual', 'Ritual'), ('administrative', 'Administrativa')], default='general', max_length=20, verbose_name='tipo de notificación')),
                ('send_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de expiración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='communications.event', verbose_name='evento relacionado')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-send_date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='leída')),
                ('read_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de lectura')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_statuses', to='communications.notification', verbose_name='notificación')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_statuses', to=settings.AUTH_USER_MODEL, verbose_name='destinatario')),
            ],
            options={
                'verbose_name': 'destinatario de notificación',
                'verbose_name_plural': 'destinatarios de notificación',
                'unique_together': {('notification', 'recipient')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(related_name='notifications', through='communications.NotificationRecipient', to=settings.AUTH_USER_MODEL, verbose_name='destinatarios'),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='destacado')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='communications.calendar', verbose_name='calendario')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='communications.event', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'evento de calendario',
                'verbose_name_plural': 'eventos de calendario',
                'unique_together': {('calendar', 'event')},
            },
        ),
    ]
