# Generated by Django 5.2 on 2025-04-28 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('document_type', models.CharField(choices=[('diploma', 'Diploma'), ('certificate', 'Certificado'), ('id_card', 'Carnet'), ('other', 'Otro')], default='other', max_length=20, verbose_name='tipo de documento')),
                ('file', models.FileField(upload_to='member_documents/', verbose_name='archivo')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='fecha de emisión')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_documents', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'documento de miembro',
                'verbose_name_plural': 'documentos de miembros',
                'ordering': ['-issue_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='profesión')),
                ('civil_id', models.CharField(blank=True, max_length=20, verbose_name='documento de identidad')),
                ('mother_lodge', models.CharField(blank=True, max_length=100, verbose_name='logia madre')),
                ('masonic_id', models.CharField(blank=True, max_length=20, verbose_name='número de registro masónico')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='nombre de contacto de emergencia')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono de contacto de emergencia')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, verbose_name='relación con contacto de emergencia')),
                ('last_attendance_date', models.DateField(blank=True, null=True, verbose_name='fecha de última asistencia')),
                ('attendance_count', models.PositiveIntegerField(default=0, verbose_name='conteo de asistencias')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil de miembro',
                'verbose_name_plural': 'perfiles de miembros',
                'permissions': [('view_detailed_profile', 'Puede ver detalles completos del perfil')],
            },
        ),
        migrations.CreateModel(
            name='MemberProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('date', models.DateField(verbose_name='fecha')),
                ('ceremony_type', models.CharField(blank=True, max_length=100, verbose_name='tipo de ceremonia')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='lugar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_progress', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'progreso de miembro',
                'verbose_name_plural': 'progresos de miembros',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='presente')),
                ('excuse', models.TextField(blank=True, verbose_name='excusa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='communications.event', verbose_name='evento')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'ordering': ['-event__date'],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
