# Generated by Django 5.2 on 2025-04-28 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(default=0.0, verbose_name='uso de CPU')),
                ('memory_usage', models.FloatField(default=0.0, verbose_name='uso de memoria')),
                ('disk_usage', models.FloatField(default=0.0, verbose_name='uso de disco')),
                ('db_size', models.BigIntegerField(default=0, verbose_name='tamaño de base de datos')),
                ('db_connections', models.PositiveIntegerField(default=0, verbose_name='conexiones a base de datos')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='usuarios activos')),
                ('response_time', models.FloatField(default=0.0, verbose_name='tiempo de respuesta')),
                ('status', models.CharField(choices=[('healthy', 'Saludable'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='healthy', max_length=20, verbose_name='estado')),
                ('status_message', models.TextField(blank=True, verbose_name='mensaje de estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'estado del sistema',
                'verbose_name_plural': 'estados del sistema',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='nombre de archivo')),
                ('file_path', models.CharField(max_length=255, verbose_name='ruta de archivo')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='tamaño de archivo')),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Programado')], default='scheduled', max_length=20, verbose_name='tipo de respaldo')),
                ('status', models.CharField(choices=[('success', 'Éxito'), ('failure', 'Fallo'), ('in_progress', 'En progreso')], default='in_progress', max_length=20, verbose_name='estado')),
                ('error_message', models.TextField(blank=True, verbose_name='mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'respaldo',
                'verbose_name_plural': 'respaldos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='weekly', max_length=20, verbose_name='frecuencia')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0, verbose_name='día de la semana')),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, verbose_name='día del mes')),
                ('hour', models.PositiveSmallIntegerField(default=0, verbose_name='hora')),
                ('minute', models.PositiveSmallIntegerField(default=0, verbose_name='minuto')),
                ('keep_daily', models.PositiveIntegerField(default=7, verbose_name='mantener respaldos diarios')),
                ('keep_weekly', models.PositiveIntegerField(default=4, verbose_name='mantener respaldos semanales')),
                ('keep_monthly', models.PositiveIntegerField(default=12, verbose_name='mantener respaldos mensuales')),
                ('backup_path', models.CharField(default='/backups', max_length=255, verbose_name='ruta de respaldos')),
                ('include_media', models.BooleanField(default=True, verbose_name='incluir archivos multimedia')),
                ('compress', models.BooleanField(default=True, verbose_name='comprimir respaldo')),
                ('encrypt', models.BooleanField(default=False, verbose_name='cifrar respaldo')),
                ('notify_on_success', models.BooleanField(default=False, verbose_name='notificar en éxito')),
                ('notify_on_failure', models.BooleanField(default=True, verbose_name='notificar en fallo')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico para notificaciones')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_backup_configurations', to=settings.AUTH_USER_MODEL, verbose_name='actualizada por')),
            ],
            options={
                'verbose_name': 'configuración de respaldos',
                'verbose_name_plural': 'configuraciones de respaldos',
            },
        ),
        migrations.CreateModel(
            name='LodgeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodge_name', models.CharField(max_length=200, verbose_name='nombre de la Logia')),
                ('lodge_number', models.CharField(blank=True, max_length=50, verbose_name='número de la Logia')),
                ('foundation_date', models.DateField(blank=True, null=True, verbose_name='fecha de fundación')),
                ('grand_lodge_name', models.CharField(blank=True, max_length=200, verbose_name='nombre de la Gran Logia')),
                ('jurisdiction', models.CharField(blank=True, max_length=200, verbose_name='jurisdicción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='lodge_logos/', verbose_name='logo')),
                ('primary_color', models.CharField(default='#1a237e', max_length=20, verbose_name='color primario')),
                ('secondary_color', models.CharField(default='#ffc107', max_length=20, verbose_name='color secundario')),
                ('email_from', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico remitente')),
                ('email_signature', models.TextField(blank=True, verbose_name='firma de correo electrónico')),
                ('calendar_start_month', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1, verbose_name='mes de inicio del calendario')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='modo mantenimiento')),
                ('debug_mode', models.BooleanField(default=False, verbose_name='modo depuración')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_configurations', to=settings.AUTH_USER_MODEL, verbose_name='actualizada por')),
            ],
            options={
                'verbose_name': 'configuración de Logia',
                'verbose_name_plural': 'configuraciones de Logia',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico'), ('security', 'Seguridad')], default='info', max_length=20, verbose_name='tipo de registro')),
                ('module', models.CharField(max_length=100, verbose_name='módulo')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('details', models.TextField(blank=True, verbose_name='detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='agente de usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro del sistema',
                'verbose_name_plural': 'registros del sistema',
                'ordering': ['-created_at'],
            },
        ),
    ]
